INCLUDE(FindPackageHandleStandardArgs)

FILE(
	GLOB
	SOQT_INCLUDE_PATHS
	$ENV{COINDIR}/include
	$ENV{COIN3DDIR}/include
	$ENV{HOME}/include
	/usr/local/include
	/usr/include/Coin*
	/usr/include
	$ENV{SystemDrive}/Coin*/include
	$ENV{ProgramW6432}/Coin*/include
	$ENV{ProgramFiles}/Coin*/include
)

FILE(
	GLOB
	SOQT_LIBRARY_PATHS
	$ENV{COINDIR}/lib
	$ENV{COIN3DDIR}/lib
	$ENV{HOME}/lib
	/usr/local/lib
	/usr/lib
	$ENV{SystemDrive}/Coin*/lib
	$ENV{ProgramW6432}/Coin*/lib
	$ENV{ProgramFiles}/Coin*/lib
)

FIND_PATH(
	SOQT_INCLUDE_DIRS
	NAMES
	Inventor/Qt/SoQt.h
	HINTS
	${SOQT_INCLUDE_PATHS}
)

FIND_LIBRARY(
	SOQT_LIBRARY_DEBUG
	NAMES
	SoQtd soqt1d
	HINTS
	${SOQT_LIBRARY_PATHS}
)

FIND_LIBRARY(
	SOQT_LIBRARY_RELEASE
	NAMES
	SoQt soqt1
	HINTS
	${SOQT_LIBRARY_PATHS}
)

IF(WIN32)
	SET(SOQT_DEFINITIONS -DSOQT_NOT_DLL)
ENDIF(WIN32)

IF(SOQT_LIBRARY_DEBUG AND NOT SOQT_LIBRARY_RELEASE)
	SET(SOQT_LIBRARIES ${SOQT_LIBRARY_DEBUG})
ENDIF(SOQT_LIBRARY_DEBUG AND NOT SOQT_LIBRARY_RELEASE)

IF(SOQT_LIBRARY_RELEASE AND NOT SOQT_LIBRARY_DEBUG)
	SET(SOQT_LIBRARIES ${SOQT_LIBRARY_RELEASE})
ENDIF(SOQT_LIBRARY_RELEASE AND NOT SOQT_LIBRARY_DEBUG)

IF(SOQT_LIBRARY_DEBUG AND SOQT_LIBRARY_RELEASE)
	SET(SOQT_LIBRARIES debug ${SOQT_LIBRARY_DEBUG} optimized ${SOQT_LIBRARY_RELEASE})
ENDIF(SOQT_LIBRARY_DEBUG AND SOQT_LIBRARY_RELEASE)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	SoQt
	DEFAULT_MSG
	SOQT_INCLUDE_DIRS
	SOQT_LIBRARIES
)

MARK_AS_ADVANCED(
	SOQT_DEFINITIONS
	SOQT_INCLUDE_DIRS
	SOQT_LIBRARIES
	SOQT_LIBRARY_DEBUG
	SOQT_LIBRARY_RELEASE
) 
