INCLUDE(FindPackageHandleStandardArgs)

FILE(
	GLOB
	BULLET_INCLUDE_PATHS
	$ENV{BULLETDIR}/include/bullet
	$ENV{HOME}/include/bullet
	/usr/local/include/bullet
	/usr/include/bullet
	$ENV{ProgramW6432}/bullet*/include/bullet
	$ENV{ProgramFiles}/bullet*/include/bullet
	$ENV{ProgramW6432}/rl*/include/bullet
	$ENV{ProgramFiles}/rl*/include/bullet
)

FILE(
	GLOB
	BULLET_LIBRARY_PATHS
	$ENV{BULLETDIR}/lib
	$ENV{HOME}/lib
	/usr/local/lib
	/usr/lib
	$ENV{ProgramW6432}/bullet*/lib
	$ENV{ProgramFiles}/bullet*/lib
	$ENV{ProgramW6432}/rl*/lib
	$ENV{ProgramFiles}/rl*/lib
)

FIND_PATH(
	BULLET_INCLUDE_DIRS
	NAMES
	Bullet-C-Api.h
	HINTS
	${BULLET_INCLUDE_PATHS}
)

FIND_LIBRARY(
	BULLET_COLLISION_LIBRARY_DEBUG
	NAMES
	bulletcollisiond BulletCollisiond BulletCollision_debug
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_COLLISION_LIBRARY_RELEASE
	NAMES
	bulletcollision BulletCollision
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_CONVEXDECOMPOSITION_LIBRARY_DEBUG
	NAMES
	convexdecompositiond ConvexDecompositiond ConvexDecomposition_debug
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_CONVEXDECOMPOSITION_LIBRARY_RELEASE
	NAMES
	convexdecomposition ConvexDecomposition
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_DYNAMICS_LIBRARY_DEBUG
	NAMES
	bulletdynamicsd BulletDynamicsd BulletDynamics_debug
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_DYNAMICS_LIBRARY_RELEASE
	NAMES
	bulletdynamics BulletDynamics
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_MATH_LIBRARY_DEBUG
	NAMES
	bulletmathd LinearMathd LinearMath_debug
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_MATH_LIBRARY_RELEASE
	NAMES
	bulletmath LinearMath
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_SOFTBODY_LIBRARY_DEBUG
	NAMES
	bulletsoftbodyd BulletSoftBodyd BulletSoftBody_debug
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FIND_LIBRARY(
	BULLET_SOFTBODY_LIBRARY_RELEASE
	NAMES
	bulletsoftbody BulletSoftBody
	HINTS
	${BULLET_LIBRARY_PATHS}
)

FOREACH(LIBRARY BULLET_COLLISION_LIBRARY BULLET_CONVEXDECOMPOSITION_LIBRARY BULLET_DYNAMICS_LIBRARY BULLET_MATH_LIBRARY BULLET_SOFTBODY_LIBRARY)
	SET(BULLET_LIBRARY ${LIBRARY})
	
	IF(${LIBRARY}_DEBUG AND NOT ${LIBRARY}_RELEASE)
		SET(${BULLET_LIBRARY} ${${LIBRARY}_DEBUG})
	ENDIF(${LIBRARY}_DEBUG AND NOT ${LIBRARY}_RELEASE)
	
	IF(${LIBRARY}_RELEASE AND NOT ${LIBRARY}_DEBUG)
		SET(${BULLET_LIBRARY} ${${LIBRARY}_RELEASE})
	ENDIF(${LIBRARY}_RELEASE AND NOT ${LIBRARY}_DEBUG)
	
	IF(${LIBRARY}_DEBUG AND ${LIBRARY}_RELEASE)
		SET(${BULLET_LIBRARY} debug ${${LIBRARY}_DEBUG} optimized ${${LIBRARY}_RELEASE})
	ENDIF(${LIBRARY}_DEBUG AND ${LIBRARY}_RELEASE)
ENDFOREACH(LIBRARY)

SET(
	BULLET_LIBRARIES
	${BULLET_COLLISION_LIBRARY}
	${BULLET_CONVEXDECOMPOSITION_LIBRARY}
	${BULLET_DYNAMICS_LIBRARY}
	${BULLET_MATH_LIBRARY}
	${BULLET_SOFTBODY_LIBRARY}
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	Bullet
	DEFAULT_MSG
	BULLET_INCLUDE_DIRS
	BULLET_COLLISION_LIBRARY
#	BULLET_CONVEXDECOMPOSITION_LIBRARY
	BULLET_DYNAMICS_LIBRARY
	BULLET_MATH_LIBRARY
	BULLET_SOFTBODY_LIBRARY
)

MARK_AS_ADVANCED(
	BULLET_INCLUDE_DIRS
	BULLET_COLLISION_LIBRARY
	BULLET_COLLISION_LIBRARY_DEBUG
	BULLET_COLLISION_LIBRARY_RELEASE
	BULLET_CONVEXDECOMPOSITION_LIBRARY
	BULLET_CONVEXDECOMPOSITION_LIBRARY_DEBUG
	BULLET_CONVEXDECOMPOSITION_LIBRARY_RELEASE
	BULLET_DYNAMICS_LIBRARY
	BULLET_DYNAMICS_LIBRARY_DEBUG
	BULLET_DYNAMICS_LIBRARY_RELEASE
	BULLET_LIBRARIES
	BULLET_MATH_LIBRARY
	BULLET_MATH_LIBRARY_DEBUG
	BULLET_MATH_LIBRARY_RELEASE
	BULLET_SOFTBODY_LIBRARY
	BULLET_SOFTBODY_LIBRARY_DEBUG
	BULLET_SOFTBODY_LIBRARY_RELEASE
) 
